package cr.ac.ucr.paraiso.dsw4.renting.dto;
import java.util.List;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

public class PeliculaCreationDTO {
   // I'm removing peliculaId for creation, as it's often auto-generated by the DB
   @NotBlank(message = "Title is mandatory")
   @Size(min = 1, max = 50, message = "Title must be between 1 and 50 characters")
   private String titulo;
   private boolean subtitulada;
   private boolean estreno;
   @NotNull(message = "Genre is mandatory")
   @Valid // Important: Validates the nested GeneroDTO
   private GeneroDTO genero;
   @NotNull(message = "Actors are mandatory")
   @Size(min = 1, message = "At least one actor is required")
   @Valid // Important: Validates the nested ActorDTO list
   private List<ActorDTO> actores;
   
   //Getters and Setters

   public String getTitulo() {
    return titulo;
   }
   public void setTitulo(String titulo) {
    this.titulo = titulo;
   }
   public boolean isSubtitulada() {
    return subtitulada;
   }
   public void setSubtitulada(boolean subtitulada) {
    this.subtitulada = subtitulada;
   }
   public boolean isEstreno() {
    return estreno;
   }
   public void setEstreno(boolean estreno) {
    this.estreno = estreno;
   }
   public GeneroDTO getGenero() {
    return genero;
   }
   public void setGenero(GeneroDTO genero) {
    this.genero = genero;
   }
   public List<ActorDTO> getActores() {
    return actores;
   }
   public void setActores(List<ActorDTO> actores) {
    this.actores = actores;
   }
   

// Nested DTOs (Important!)
   public static class GeneroDTO {
       @NotNull(message = "Genre ID is mandatory")
       private int generoId;
       public int getGeneroId() {
           return generoId;
       }
       public void setGeneroId(int generoId) {
           this.generoId = generoId;
       }
   }
   public static class ActorDTO {
       @NotNull(message = "Actor ID is mandatory")
       private int actorId;
       public int getActorId() {
           return actorId;
       }
       public void setActorId(int actorId) {
           this.actorId = actorId;
       }
   }
}



